In [56]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout
from keras.utils import np_utils

import wandb
from wandb.keras import WandbCallback
import numpy as np

### Logging code

In [57]:
run = wandb.init()
config = run.config

config.epochs = 10

W&B Run: https://app.wandb.ai/martin-fabbri-a/dl-playground-dl-debug/runs/34bul928
Call `%%wandb` in the cell containing your training loop to display live results.


### Load Data

In [58]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [59]:
is_five_train = y_train == 5
is_five_train

array([ True, False, False, ...,  True, False, False])

In [60]:
is_five_test = y_test == 5
is_five_test

array([False, False, False, ..., False,  True, False])

In [61]:
labels = ["not five", "five"]


In [62]:
X_train.shape

(60000, 28, 28)

In [63]:
img_width = X_train.shape[1]
img_width

28

In [64]:
img_height = X_train.shape[2]
img_height

28

### Create Model

In [65]:
model = Sequential()
model .add(Flatten(input_shape=(img_width, img_height)))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])

In [66]:
model.fit(X_train, is_five_train, epochs=config.epochs, validation_data=(X_test, is_five_test), callbacks=[WandbCallback(labels=labels)])

Resuming run: https://app.wandb.ai/martin-fabbri-a/dl-playground-dl-debug/runs/34bul928
Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 3s 49us/step - loss: 0.0638 - acc: 0.9359 - val_loss: 0.0509 - val_acc: 0.9489
Epoch 2/10
60000/60000 [==============================] - 3s 43us/step - loss: 0.0492 - acc: 0.9506 - val_loss: 0.0426 - val_acc: 0.9571
Epoch 3/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.0430 - acc: 0.9569 - val_loss: 0.0483 - val_acc: 0.9514
Epoch 4/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.0442 - acc: 0.9555 - val_loss: 0.0390 - val_acc: 0.9608
Epoch 5/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.0405 - acc: 0.9593 - val_loss: 0.0483 - val_acc: 0.9512
Epoch 6/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.0400 - acc: 0.9598 - val_loss: 0.0341 - val_acc: 0.9659
Epoch 7/10
60000/60000 [================

In [67]:
print(model.predict(X_test[:50, :, :]))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [68]:
print(is_five_train[:50])

[ True False False False False False False False False False False  True
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
 False False False False False False False False False False False  True
 False False]
